
<table summary="Submitted table designs">
<caption>Table designs</caption>
<thead>
<tr>
<th scope="col">Design Name</th><th scope="col">Author</th><th scope="col">Country</th><th scope="col">Comment</th><th scope="col">Download</th>
</tr>
</thead>
<tfoot>
<tr><th scope="row">Total</th><td colspan="4">67 designs</td></tr>
</tfoot>

<tbody>
<tr >
<th scope="row" id="r100"><a href="100.php">rows table template</a></th>
<td><a href="http://www.adobati.it">Omar '0m4r' Adobati</a></td><td>Italy</td><td>Simple, clean and a quite classic table template :)</td><td><a href="http://www.adobati.it/labs/CSSTable/0m4r.table.css" title="Download the rows table template CSS file">Download</a></td>
</tr>
<tr class="odd">
<th scope="row" id="r99"><a href="99.php">Blue Dream</a></th>
<td><a href="http://www.admixweb.com">Teylor Feliz</a></td><td>USA</td><td>Beautiful combination of Blue and Brown.</td><td><a href="http://www.admixweb.com/downloads/csstablegallery/bluedream.css" title="Download the Blue Dream CSS file">Download</a></td>
</tr>
</tbody>
</table>

