<?   
	// Configuracion para IS de open
	// SQL Server de Open( 192.168.0.100 = ServerOpen )
	
	$usr = "cebWeb"; 
	$pwd = "6736"; 
	$db = "BDCEB";
	$host = "serveropen"; 
	$modofecha = 103;
	//$tmpPath = "C:\\inetpub\\wwwroot\\abeceb\\tmp\\";
	$tmpPath = "tmp/";
	$dirChar = "/";
	
	
	
	// Configuracion para Web Apache ubicado en barragan
	// Sql Server CEB ( 192.168.0.10)
	// a traves del Firewall del XP
	/*
	$usr = "sa"; 
    	$pwd = ""; 
    	$db = "BDCEB"; 
    	$host = "200.61.183.157"; 
    	$modofecha = 103;
    	//$tmpPath = "/usr/local/www/abeceb/tmp/";
    	$tmpPath = "tmp/";
    	$dirChar = "/";
	*/
	
	// Configuracion para Web Apache ubicado en abeceb
	// Sql Server CEB ( 192.168.0.10)
	// a traves del Firewall del XP
	/*
	$usr = "sa"; 
    	$pwd = ""; 
    	$db = "BDCEB"; 
    	$host = "192.168.0.1"; 
    	$modofecha = 103;
    	//$tmpPath = "/usr/local/www/abeceb/tmp/";
    	$tmpPath = "tmp/";
    	$dirChar = "/";
	*/
	
	
	// Configuracion para IS de Open 
	// y SQL Server Ceb (192.168.0.10 = server)
	/*
        $usr = "sa"; 
        $pwd = ""; 
        $db = "BDCEB"; 
        $host = "server"; 
	$modofecha = 103;
	$tmpPath = "C:\\inetpub\\wwwroot\\abeceb\\tmp\\";
	$dirChar = "\";

        */
      
?>    